### ISSUE TITLE
Messing around system events

### ISSUE THREAD

**Issue by amunhoz** [yoshihitoh/zstd-codec#11]
Hi there, first good work! thanks for that.

But, it looks like there is something messing around with rejection/errors treatment in nodejs in your code:
https://github.com/nodejs/node/issues/21950

**Comment by yoshihitoh** [comment]
Hello @amunhoz , thanks for using the module, and creating the issue!

I tried your repro code, and reduced version, but the bug does not occur on my environment. 
- macOS: 10.12.6
- Node.js: v8.11.3

I'm going to survey the issue on Ubuntu 16.04 (on VM), but it will be hard to resolve.
`unhandledRejection` is auto-generated by Emscripten, I couldn't get the answer from the documents.

IIRC there is two problems.
1. zstd-codec injects `process["exit"](1)` as `unhandledRejection` event hanlder. this code enforces the application process to exit on `unhandledRejection` event.
2. any error occurs on initialization of zstd-codec when using async/promise.

If you are not using `unhandledRejection`, please remove the listener attached to process for workaround.

**Comment by yoshihitoh** [comment]
Ah, sorry I was misunderstanding.
Your repro code and reduced code are working.

Currently `unhandledRejection` handler is always attached on Node.js.
https://github.com/kripken/emscripten/blob/699d457f4ff55e0422ea79517714b07d691e8dae/src/shell.js#L103-L179

The code generation is added by this PR.
https://github.com/kripken/emscripten/pull/5948

I think it is possible to avoid this issue by downgrading Emscripten, but it is hard to do that or not...

**Comment by yoshihitoh** [comment]
Issue#8 native bindings for Node.js will solve this issue, so I close this issue.
