### ISSUE TITLE
failed to asynchronously prepare wasm: TypeError: handle[name] is not a function

### ISSUE THREAD

**Issue by eneroth** [yoshihitoh/zstd-codec#20]
<img width="1456" alt="Screenshot 2019-04-27 at 18 36 46" src="https://user-images.githubusercontent.com/333974/56851055-a254a300-691b-11e9-9a8f-794b2b2cda4a.png">

I'm not sure exactly what's wrong here (see above). `test_data` is just an int representation of "hello world".

**Comment by yoshihitoh** [comment]
@eneroth Hello
`compress` method expects Uint8Array on the 1st argument.
I think `test_data` is a normal array.

Would you try below code?
```
simple.compress(new Uint8Array(test_data), 5);
```

**Comment by eneroth** [comment]
That worked, thank you! Weird, I created `tesst_data` using `stringToUtf8ByteArray` from Google Closure compiler. I just assumed that it would do what it says on the tin.
