### ISSUE TITLE
Missing readme on npmjs

### ISSUE THREAD

**Issue by DanielRuf** [yoshihitoh/zstd-codec#21]
https://github.com/yoshihitoh/zstd-codec/blob/develop/js/package.json

https://www.npmjs.com/package/zstd-codec

**Comment by yoshihitoh** [comment]
Hi @DanielRuf .
Sorry for the too late response, and thank you for reporting the issue.

Now I'm trying to restructure this project. After complete the task, I will attach the README to the npm package.
