### ISSUE TITLE
Using provided example with other file formats.

### ISSUE THREAD

**Issue by priyesh-diukar** [yoshihitoh/zstd-codec#5]
var BASE64_MARKER = ';base64,';
    convertDataURIToBinary(dataURI) {
        var base64Index = dataURI.indexOf(BASE64_MARKER) + BASE64_MARKER.length;
        var base64 = dataURI.substring(base64Index);
        var raw = window.atob(base64);
        var rawLength = raw.length;
        var array = new Uint8Array(new ArrayBuffer(rawLength));
        for (var i = 0; i < rawLength; i++) {
            array[i] = raw.charCodeAt(i);
        }
        return array;
    }

    handleImageChange(event) {
        var reader = new FileReader();
        var file = event.target.files[0];
        reader.onloadend = (resultObj) => {
            var simple = new ZstdCodec.Simple();
            var bmp_bytes =
                simple.decompress(convertDataURIToBinary(resultObj.currentTarget.result));
            var bmp_b64 = 'data:image/bmp;base64,' + uint8ArrayToBase64(bmp_bytes);

            var image = document.createElement('img');
            image.src = bmp_b64;

            var container = document.getElementById('container');
            container.appendChild(image);
        };
        reader.readAsDataURL(file);
    }

<input id="fileinput" type="file"
                               onChange="handleImageChange(event)"/>
        <div id="container"></div>

@yoshihitoh,
Firstly, thanks for providing an example for usage.
I tried using the provided example on a jpg image.
Unfortunately i get a null return value on simple.decompress(Uint8Array);
Am i missing something?
How do i use the example with other file formats?

**Comment by yoshihitoh** [comment]
@priyesh-diukar  Hello!
Thanks for your feedback.

Would you please tell me about followings?
- zstd version
- jpeg file size

I think that zstd can decompress jpeg files well.
`zstd-codec` uses zstd `1.3.3`, might be version related problem.

Although it is not a direct cause, you need to change image creation to use jpeg files on example.
Please use `data:image/jpeg;` instead of `data:image/bmp;` 
```javascript
// for bmp
var bmp_b64 = 'data:image/bmp;base64,' + uint8ArrayToBase64(bmp_bytes);

// for jpeg
var bmp_b64 = 'data:image/jpeg;base64,' + uint8ArrayToBase64(bmp_bytes);
```

**Comment by yoshihitoh** [comment]
@priyesh-diukar 
Could you please retrieve `content-size` from a compressed jpeg file via `contentSize` API?

`decompress` returns `null` value when failed to decompress data.
possible causes are followings
- cannot retrieve `content-size` from compressed data. (decompress requires content-size to decide memory size)
- ZSTD_decompress (original API) returns error

If you cannot retrieve content-size via `contentSize` API, streaming API may resolve the issue.

```javascript
handleImageChange(event) {
    var reader = new FileReader();
    var file = event.target.files[0];
    reader.onloadend = (resultObj) => {
        var compressed_bytes = convertDataURIToBinary(resultObj.currentTarget.result);

        // retrieve content size before decompression
        var generic = new ZstdCodec.Generic();
        var content_size = generic.contentSize(compressed_bytes);

        var simple = new ZstdCodec.Simple();
        var bmp_bytes = simple.decompress(compressed_bytes);
        var bmp_b64 = 'data:image/bmp;base64,' + uint8ArrayToBase64(bmp_bytes);

        var image = document.createElement('img');
        image.src = bmp_b64;

        var container = document.getElementById('container');
        container.appendChild(image);
    };
    reader.readAsDataURL(file);
}
```

**Comment by priyesh-diukar** [comment]
@yoshihitoh ,
Thanks, for the update.
I am using, v0.0.6.
I believe, I interpreted this wrongly.
Here is what i want to achieve.

1. Feed handleImageChange(event) a jpeg image (~1-2MB).
2. Compress it using ZstdCodec; (Reduce the file size here without sacrificing much quality).
3. Re-render the compressed image in an image tag back in jpeg format.

Here is what i tried,
I am not able to generate, the compressed jpeg back in a valid "jpeg" format.
The jpeg_b64 generated is not a valid jpeg image.
My generated image width and height is 0 x 0;

Here is my updated code: 
```
var BASE64_MARKER = ';base64,';
convertDataURIToBinary(dataURI) {
    var base64Index = dataURI.indexOf(BASE64_MARKER) + BASE64_MARKER.length;
    var base64 = dataURI.substring(base64Index);
    var raw = window.atob(base64);
    var rawLength = raw.length;
    var array = new Uint8Array(new ArrayBuffer(rawLength));
    for (var i = 0; i < rawLength; i++) {
        array[i] = raw.charCodeAt(i);
    }
    return array;
}

function handleImageChange(event) {
    var reader = new FileReader();
    var file = event.target.files[0];
    reader.onloadend = (resultObj) => {
      var simple = new ZstdCodec.Simple();
      var content_bytes = convertDataURIToBinary(resultObj.currentTarget.result);
      var compressed_bytes = simple.compress(content_bytes, 5);
      var jpeg_bytes = simple.decompress(compressed_bytes);
      var jpeg_b64 = 'data:image/jpeg;base64,' + uint8ArrayToBase64(jpeg_bytes);
      var image = document.createElement('img');
      image.src = jpeg_b64;
      var container = document.getElementById('container');
      container.appendChild(image);
    };
    reader.readAsDataURL(file);
}
```
Is this the right way to do this?

**Comment by yoshihitoh** [comment]
@priyesh-diukar Thank you for checking.

Hmm, your code looks correct.
Is `jpeg_bytes` still null value?

zstd is file format independent compression algorithm, so above code should be work. 
I want you to check
- use `content_bytes` instead of `jpeg_bytes` to generate base64 encoded data
- length of compressed_bytes
- length of jpeg_bytes

I will survey this problem on this weekend, using 1-2MiB jpeg files.

**Comment by cm-hirakawa-yoshihito** [comment]
> use content_bytes instead of jpeg_bytes to generate base64 encoded data

I want you to try this to ensure that the image generation is correct, compressed data or decompressed data or both of them are broken.

**Comment by priyesh-diukar** [comment]
```
function handleImageChange(event) {
    var reader = new FileReader();
    var file = event.target.files[0];
    reader.onloadend = (resultObj) => {

      var simple = new ZstdCodec.Simple();
      var content_bytes = convertDataURIToBinary(resultObj.currentTarget.result);
      var compressed_bytes = simple.compress(content_bytes, 5);

      var jpeg_bytes = simple.decompress(compressed_bytes);

      // This works fine jpeg is rendered, but generated image is not compressed.
      // No visible reduction in byte size. Size is same as originally fed jpeg.
      var jpeg_b64_compressed = 'data:image/jpeg;base64,' + uint8ArrayToBase64(jpeg_bytes);

      // This works fine too, original jpeg is rendered.
      var jpeg_b64_original = 'data:image/jpeg;base64,' + uint8ArrayToBase64(content_bytes);

      var compressed_jpeg_image = document.createElement('img');
      compressed_jpeg_image.src = jpeg_b64_compressed;

      var original_jpeg_image = document.createElement('img');
      original_jpeg_image.src = jpeg_b64_original;

      var container = document.getElementById('container');
      container.appendChild(compressed_jpeg_image);
      container.appendChild(original_jpeg_image);

    };
    reader.readAsDataURL(file);
}
```

@yoshihitoh , 
I tried both. There are no visible errors or warnings in the console.
But in the first case, there is no visible compression on the output image.

**Comment by yoshihitoh** [comment]
@priyesh-diukar Hello,
I tried compress and decompress a jpeg file (about 4.6MiB) using `zstd-codec 0.0.6`, and that work ed correctly.

Here is my code.
```javascript
function showBitmap() {
    getData('/DSCN0056.JPG', (data) => {
        var simple = new ZstdCodec.Simple();
        var compressed_bytes = simple.compress(data);
        var jpg_bytes = simple.decompress(compressed_bytes);
        var jpg_b64 = 'data:image/jpeg;base64,' + uint8ArrayToBase64(jpg_bytes);

        var image = document.createElement('img');
        image.src = jpg_b64;

        var container = document.getElementById('container');
        container.appendChild(image);
    });
}
```

**Comment by yoshihitoh** [comment]
Ah, I think that I was misunderstanding.
Is it possible to render zstd-compressed jpeg image directly?
I thinks it is not possible, need to decompress before render.

**Comment by yoshihitoh** [comment]
I thinks that you thought `zstd-codec` is an image codec, but unfortunately it is not.

Closing the issue, feel free to reopen.
