### ISSUE TITLE
command "yarn add zstd-codec" get version 0.0.7 not the latest version 0.0.8

### ISSUE THREAD

**Issue by progamer71** [yoshihitoh/zstd-codec#6]
yarn add zstd-codec

yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.5.1" while you're on "1.3.2".
info To upgrade, run the following command:
$ curl -o- -L https://yarnpkg.com/install.sh | bash
success Saved 1 new dependency.
└─ zstd-codec@0.0.7
✨  Done in 24.62s.

**Comment by yoshihitoh** [comment]
@progamer71  Hello!
Sorry, I had not published `0.0.8`.

Version `0.0.8` is available now, please try again.
https://www.npmjs.com/package/zstd-codec

**Comment by progamer71** [comment]
@yoshihitoh Hi,
I've got version 0.0.8 now.
Thanks you

**Comment by yoshihitoh** [comment]
@progamer71 Hi,
Thanks for your reporting and closing the issue.
If you need any feature or API improvement, feel free to make a new issue!
