### ISSUE TITLE
Exclude examples folder from NPM package. 126MB!

### ISSUE THREAD

**Issue by sirian** [yoshihitoh/zstd-codec#79]
![image](https://user-images.githubusercontent.com/897643/71323749-c8046d00-24e7-11ea-9ad9-4112edf1db39.png)

**Comment by sirian** [comment]
@yoshihitoh look pls

**Comment by yoshihitoh** [comment]
@sirian

**Comment by yoshihitoh** [comment]
Published!
Feel free to reopen this issue please if there are any problems.
