### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by camolin3** [yoshihitoh/zstd-codec#9]
Hi! I was wondering how to use this library.
Is there any documentation, or maybe examples of how to use it?
Thanks!

**Comment by yoshihitoh** [comment]
@camolin3  Hello!
Sorry, there is no documents, [README](../blob/develop/README.md) and [example](../tree/develop/js/example) only.

**Comment by yoshihitoh** [comment]
Closing the issue, please feel free to reopen this.
